/*
 * Powered By [rapid-framework]
 * Web Site: http://www.rapid-framework.org.cn
 * Google Code: http://code.google.com/p/rapid-framework/
 * Since 2008 - 2013
 */

package com.neusoft.portal.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neusoft.base.common.Pager;
import com.neusoft.base.common.PropertyUtils;
import com.neusoft.base.dao.HBaseDAO;
import com.neusoft.portal.model.Permission;
import com.neusoft.portal.query.PermissionQuery;

/**
 * database table: tb_permission
 * database table comments: Permission
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
@Repository
public class PermissionDao extends HBaseDAO<Permission>{
	
	public void saveOrUpdate(Permission entity) {
		if(entity.getTbid() == null){
			save(entity);
		}else{
			update(entity);
		}
	}
	
    public Permission getById(Long id) {
		
		return (Permission)getById(Permission.class, id);
	}

	@SuppressWarnings("unchecked")
	public List<Permission> findList(PermissionQuery appQuery) {		
		return findList(Permission.class, PropertyUtils.toParameterMap(appQuery));
	}


	public Pager<Permission> findPage(PermissionQuery appQuery) {
		Pager<Permission> pager = new Pager<Permission>();
		Map map = PropertyUtils.toParameterMap(appQuery);
		List<Permission> appList = findList(Permission.class, map, appQuery.getPage().intValue(), appQuery.getRows().intValue());
		pager.setTotalRecords(getTotalCount(Permission.class, map));
		pager.setCurrentPage(appQuery.getPage());
		pager.setPageSize(appQuery.getRows());
		pager.setRecords(appList);
		return pager;
	}
	 

}
