Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (481, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '1712', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (483, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1709', '1674,1675,1676,1677,1678,1679,1680,1681,1682', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (501, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1704', '1701,1702,1703', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (505, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'chrome', 3, NULL, 
    '1883,2141', '2690', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (508, NULL, 'x', 'right', 8, 
    1, 'lashen', 'default', 4, NULL, 
    '3121', '1873', '1875,1874,1876,2131', '2067,2069,2070,2071,2072,2073', '1829,1855', 
    NULL, NULL, '订单查询', '订舱/报关', '快递叫件', 
    '中标信息', NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (521, NULL, 'x', 'right', 8, 
    1, 'pingpu', 'default', 3, NULL, 
    '2196,2402,2440', '2124,2297,2300,2356,2360,2367,3445', '2390,2435,2436,2437,2438', '2439,2441,2442,2443,2444', NULL, 
    NULL, NULL, '订单相关', '滚动计划', '其他', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (421, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1810', '1570,1571,3618,3619,3620', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (381, NULL, 'x', 'right', 3, 
    1, 'lashen', 'default', 3, NULL, 
    '1826,2079', '1589,1685,1686,1688,2021,2100,2167,3105,3712', '1684', '1618,1619,1687', NULL, 
    NULL, NULL, '付款保障', '信用证', '订单查询', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (190, NULL, 'x', 'right', 9, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '1127,1128', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (222, NULL, 'x', 'right', 8, 
    1, 'pingpu', 'default', 3, NULL, 
    '1754,1961,2110', '1149,1151,1247,1429,1430,1960,2114,2454', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面6', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (182, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '978,1056,3141', NULL, NULL, NULL, 
    NULL, NULL, '信用证', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (242, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1761', '1762,1763,1764', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (261, NULL, 'x', 'right', 3, 
    1, 'lashen', 'default', 3, NULL, 
    '2683,2684,2685', '1309,2391,1308,2584,2602,2604,2605,2660,2732,2733,2734', '2531,2372,2735,2736,2737', NULL, NULL, 
    NULL, NULL, '桌面1', '订单', '桌面3', 
    '桌面6', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (301, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (302, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 4, NULL, 
    '2193,2423,2426', '1315,1316,1478,1311,2366,2420,2421,2422,2424,2425,2427,2428,2429,2430,2431,2432,2433,2434', '1312,2776,2777,2778,2779,2780,2781,2782,2783,2784', '1310', '1529', 
    NULL, NULL, '订单管理', '信用证', '滚动计划', 
    '特技单', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (21, 'Wx', 'x', 'right', 8, 
    1, 'pingpu', 'default', 3, NULL, 
    '2189,3825', '1009,1553,3742', '1509,2188,2190,2191,2192', '1067,1066', NULL, 
    NULL, NULL, '特技单', '订单查询', '滚动计划', 
    '桌面6', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (186, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2910', '1630,1631,1632,1633,1634,1635,1636,1637', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (187, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1941', '982,2106,2759,3092', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (191, NULL, 'x', 'right', 5, 
    1, 'pingpu', 'default', 3, NULL, 
    '1811', '1051,1079,1789,1836', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (223, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (281, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (188, NULL, 'x', 'right', 9, 
    1, 'juzhong', 'default', 3, NULL, 
    '2014', '1087,1088', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (189, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, '1306,1307', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (201, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2057,2058', '2101,2102,3052', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (224, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (323, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 5, NULL, 
    '2306,2307,2308', '1510,2321,2322,2323,2324', '2328,2329,2330,2331,2332,2333,2334', NULL, NULL, 
    '2309,2310,2313,2327,2327', NULL, '订单管理', '信用证', '特技单', 
    '滚动计划', '系统管理', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (184, NULL, 'x', 'right', 7, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2105,2904,3053', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (9, 'admin', 'x', 'right', 2, 
    1, 'pingpu', 'qq', 5, NULL, 
    '1659,3861,3862', '324,326,330,3163,3164', '325,261,262,802,803,804,805', '263,265,266,364,365,366,367,368', '360,361,362,363', 
    '352,369,370,371,373,447,485,872', NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (177, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2881', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (183, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1765', '1531,1532,1533,1535,1536,1538,1638,1639,1691,1692,2104,3101,3741', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (185, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2865', '980,981', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (192, NULL, 'x', 'right', 1, 
    1, 'pingpu', 'qq', 3, NULL, 
    '1889,2386', '1530,2354,2355,2384,2385,3743,3981', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (202, NULL, 'y', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    NULL, '1028,1668,1872', NULL, NULL, NULL, 
    NULL, NULL, '快递录入', '桌面6', '桌面6', 
    '桌面6', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (203, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '1857,1929', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (221, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1832', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', '桌面5', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (382, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1693', '1707,1708', NULL, '1656', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (361, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    '1610,1711', '1479,1493,1494,1497,1498,1499', NULL, NULL, NULL, 
    NULL, NULL, '订单管理', NULL, NULL, 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (383, NULL, 'x', 'right', 6, 
    1, 'lashen', 'default', 3, NULL, 
    '2456', '1661,1662,1663,1664,1665,2020,2108,2861,3091', NULL, NULL, NULL, 
    NULL, NULL, '常用', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (402, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1642,1940,2012', '1945,2216,2218,2219,2227,2228,2230,2231,2217,3093,3094,3095,3633,4041', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (441, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (461, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    '2273', '1909,2274,2700', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', NULL, NULL, 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (401, NULL, 'x', 'right', 8, 
    1, 'lashen', 'default', 3, NULL, 
    '2009,2123,2715', '2268,2269,2270,2271,2272,3301,3962', NULL, '1550,1551', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (442, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1645,2374', '1649,1650,1653,1654,1954,2113,2345,2376,2377,2378,2379,2772', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (502, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1705', '1710', NULL, '1706', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (507, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2011,2455', '1975,2762,2763,2764,2768,2769,2770', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (541, NULL, 'x', 'right', 1, 
    1, 'juzhong', 'default', 3, NULL, 
    '1771', '1767,1768,1769,1772,1773,2261', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (506, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    '1980,2316,2317', '1732,2234,2235,2236,2237,2238,2315,2318,2319,2320,2716,2721,2722,2723,2724', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', NULL, NULL, 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (543, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (462, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '1698', '1646', NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (503, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (542, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (587, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2183,2351', '1830,2097,2182', NULL, '2350,2352,2353', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (588, NULL, 'x', 'right', 7, 
    1, 'pingpu', 'default', 3, NULL, 
    '1965', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (561, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3347,3348', '2010,2075', NULL, NULL, NULL, 
    NULL, NULL, '单据查询', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (585, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (605, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1943', '1878,2305,2491,2765,2766', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (709, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2266,2267', '2263,2264,2265,2363,2364,2365', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (504, NULL, 'x', 'right', 7, 
    1, 'lashen', 'default', 3, 'http://bizhi.zhuoku.com/bizhi2008/0602/3d/3d83.jpg', 
    '2083,2285,2516,3127', '1738,2283,2462,2481,2482,2515,2515,2849,2882,3165', '2280,2281,1982,2282,2841,2842', '2418,2419,2678,2494,2492', NULL, 
    NULL, NULL, '我的应用', '滚动计划', '报表查询', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (789, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2543,2544,2545,2546', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (790, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (792, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2576,2585', '2555,2556,2557,2558,2563,2581,2586,2616', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (793, NULL, 'x', 'right', 7, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2552,2553,2554', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (796, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (814, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (860, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (861, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2713,2714', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (891, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2806,2807', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (892, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2808,2809', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (893, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2810,2811', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (898, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2821,2822', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (929, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2877,2878', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (950, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2911,2912,2913', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (951, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2914,2915', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (971, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2968,2969', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1009, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3021,3022', '3023', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1036, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3065,3062,3063', '3066,3067', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1070, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3124,3125', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1260, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3483,3484', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1350, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3643,3644', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1369, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3681,3682', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1450, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3765,3766', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1469, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3821,3822', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1470, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3823,3824', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1529, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3922,3923', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (581, NULL, 'x', 'right', 1, 
    1, 'lashen', 'default', 3, NULL, 
    '2825', '1806,1809,2279', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (584, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (655, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2001', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (736, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (769, NULL, 'x', 'right', 1, 
    1, 'pingpu', 'default', 3, NULL, 
    '2488,2489,2495', '2483,2486,2484,2485,2487,2497,2496', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (772, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (774, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (778, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (780, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (781, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2519,2520,2525', NULL, NULL, '2517,2518,2521,2522,2523,2524,2526', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (785, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (786, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (787, NULL, 'x', 'right', 7, 
    1, 'pingpu', 'default', 3, NULL, 
    '2566,2574', '2559,2565,2567,2568,2569,2570,2571,2572,2573', '2575', NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (788, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    '2547,2549', '2535,2537,2538,2539,2540,2548', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', NULL, NULL, 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (791, NULL, 'x', 'right', 1, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2560,2561,2562,2582', '2577,2578,2579,2580', NULL, NULL, 
    NULL, NULL, '订单管理', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (794, NULL, 'x', 'right', 5, 
    1, 'pingpu', 'default', 3, NULL, 
    '2607,2609', '2608,2610,2611,2612,2613,2614,2615,2767', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (795, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (810, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2651,2652', '2653,2657,2659', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (815, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (869, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2725,2726', '2729,2801', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (874, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2760,2761', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (896, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2816,2817', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (972, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2970,2971', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (990, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3003,3004', '3555', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1029, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3042,3043', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1030, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3044,3045', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1049, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3103,3104', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1069, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3122,3123', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1241, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3446,3447', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1292, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3549,3550', '3551', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1293, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3552,3553', '3554', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1330, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3631,3632', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1389, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3702,3703', '3704', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1390, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3705,3706', '3707', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1391, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3708,3709', '3710', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1429, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3744,3745', '3746', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1489, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3841,3842,3843', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1549, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '4001,4002', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1569, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '4021,4022', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1610, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '4083,4084', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (586, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '1814,1817,1816,1823,1824,1825', NULL, '1813', NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (629, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1942', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (662, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2773,2774', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (671, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2109', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (746, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2843,2844,2864', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (482, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '1969,2393', '1753,1800,1801,1802,1803,1804,1805,2013,2392,2394,2396,2397,2680,2681,2682,2823,2824', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (773, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (777, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2507', '2500,2501,2502,2504,2505,2506,2508,2509,2510', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (798, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 1, NULL, 
    NULL, '2599,2592,2595,2589,2597,2598,2587,2593,2591,2601', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', NULL, NULL, 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (800, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (241, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2241,2746', '2409,2410,2411,2412,2413,2414,2921', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面6', '桌面6', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (829, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2692', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (862, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2717,2718', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (863, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2719,2720', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (870, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2730,2731', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (872, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2741,2742,2907', '2743,2744', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (873, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2753,2754', '2755,2756,2757,2758', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (889, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2802,2803', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1, 'admin', 'x', 'right', 1, 
    1, 'lashen', 'qq', 5, 'http://p16.qhimg.com/bdr/__85/d/_open360/pet1211/15.jpg#surl=http://p16.qhimg.com/dr/205__/bdr/__85/d/_open360/pet1211/15.jpg#pid=187112#cid=14#name=', 
    '3764,3764,3764,3806', '1093,1522,1827,1828,1347,1470,1861,1451,1775,2873,1152,1733,1838,1950,1951,2304,2389,2405,2302,2304,2695,2775,2868,2869,2870,2871,2872,2874,2901,2906,2941,2981,3102,3108,3162,3236,3341,3661,3701,3711,3865,3921,3942', '1881,1109,2346,2162,2916,2963,2964,3006,3215,3802,3864,3866,3961', '2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2677,3041', '3901,3902,3903,3904', 
    '544,927,1490,926,1017,582,1854,1313,1884,1948,2942,577,2195,642,2691,1749,2738,2866,2942,3005,1226', NULL, '订单管理', '滚动计划', '付款保障', 
    '特技单', '系统管理', '桌面6');
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (897, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2819,2820', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (969, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2961,2962', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (970, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2966,2967', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1031, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3046,3047', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1033, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3050,3051', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1035, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3060,3057,3058', '3059,3061', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1124, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3211,3212', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1291, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3546,3547', '3548', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1449, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3761,3762', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (729, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (753, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2451,2452,2453', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (754, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2457,2458,2459', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (755, NULL, 'x', 'left', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (756, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2461', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (757, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2464,2465,2466', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (770, NULL, 'x', 'right', 6, 
    1, 'pingpu', 'default', 3, NULL, 
    '2511', '2499', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (771, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2673,2675', '2672,2674,2676', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (775, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (776, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (779, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (782, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (783, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (784, NULL, 'x', 'right', 5, 
    1, 'shiying', 'default', 3, NULL, 
    '2694', '2696,2697,2698,2699,2745', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (797, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (799, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 4, NULL, 
    NULL, '2747,2748,2749,2750,2751,2752', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    '桌面4', NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (809, NULL, 'x', 'right', 1, 
    1, 'pingpu', 'default', 3, NULL, 
    '2625,2626,2631', '2621,2622,2623,2624,2627,2628,2629,2630,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (811, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2702,2703', '2655,2704', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (812, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (813, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, '2663,2664,2665,2666', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (816, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (890, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2804,2805', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (88888481, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2711,2712', '1712', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (871, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2739,2740', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (894, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2812,2813', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (895, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2814,2815', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (909, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2862,2863', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (949, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2902,2903,2908', '2909', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (952, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '2917,2918,2919', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1032, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3048,3049', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1034, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3054,3055,3056', '3781', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1169, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3325,3322,3323,3326', '3324,3801', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1290, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3543,3544', '3545', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1392, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3713,3714', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1471, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3826,3827', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1509, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '3881,3882', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1589, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '4061,4062', NULL, NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
Insert into TB_MEMBER
   (TBID, USERNAME, APPXY, DOCKPOS, WALLPAPER_ID, 
    WALLPAPERSTATE, WALLPAPERTYPE, SKIN, DESKNUM, WALLPAPERWEBSITE, 
    DOCK, DESK1, DESK2, DESK3, DESK4, 
    DESK5, DESK6, DESKNAME1, DESKNAME2, DESKNAME3, 
    DESKNAME4, DESKNAME5, DESKNAME6)
 Values
   (1609, NULL, 'x', 'right', 4, 
    1, 'pingpu', 'default', 3, NULL, 
    '4081,4082,4085', '4086,4087', NULL, NULL, NULL, 
    NULL, NULL, '桌面1', '桌面2', '桌面3', 
    NULL, NULL, NULL);
COMMIT;
