Insert into TB_ROLE
   (ID, NAME, DESCRIPTION, GMT_CREATE, GMT_MODIFIED, 
    CREATE_BY, LAST_MODIFIED_BY, DELETED_FLAG, USING_FLAG)
 Values
   (1, '系统管理员', 'SYS_MANAGER', NULL, DATE_FORMAT('2014/1/15 11:01:31.000000','%Y-%m-%d %T'), 
    NULL, '管理员', '0', '0');
COMMIT;
