/*
 * Powered By [rapid-framework]
 * Web Site: http://www.rapid-framework.org.cn
 * Google Code: http://code.google.com/p/rapid-framework/
 * Since 2008 - 2013
 */

package com.neusoft.activiti.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;







/**
 * database table: WF_PROCINSTANCE
 * database table comments: 表单在工作流中的状态
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class WfProcinstance  implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "表单在工作流中的状态";
	public static final String ALIAS_ROW_ID = "唯一标识";
	public static final String ALIAS_PROCESSINSTANCE_ID = "流程实例Id";
	public static final String ALIAS_PROCESSDEFINITION_KEY = "流程类型";
	public static final String ALIAS_BUSINFORM_ID = "业务表数据";
	public static final String ALIAS_BUSINFORM_TYPE = "业务表类型";
	
    /**
     * 唯一标识       db_column: ROW_ID 
     */	
	private java.lang.String rowId;
    /**
     * 流程实例Id       db_column: PROCESSINSTANCE_ID 
     */	
	private java.lang.String processinstanceId;
    /**
     * 流程类型       db_column: PROCESSDEFINITION_KEY 
     */	
	private java.lang.String processdefinitionKey;
    /**
     * 业务表数据       db_column: BUSINFORM_ID 
     */	
	private java.lang.String businformId;
    /**
     * 业务表类型       db_column: BUSINFORM_TYPE 
     */	
	private java.lang.String businformType;
	/**
	 * 状态 是否结束 
	 * 0：已经结束
	 * 1：正在进行
	 */
	private java.lang.String status;
	//columns END

	public WfProcinstance(){
	}

	public WfProcinstance(
		java.lang.String rowId
	){
		this.rowId = rowId;
	}

	public void setRowId(java.lang.String value) {
		this.rowId = value;
	}
	
	public java.lang.String getRowId() {
		return this.rowId;
	}
	public void setProcessinstanceId(java.lang.String value) {
		this.processinstanceId = value;
	}
	
	public java.lang.String getProcessinstanceId() {
		return this.processinstanceId;
	}
	public void setProcessdefinitionKey(java.lang.String value) {
		this.processdefinitionKey = value;
	}
	
	public java.lang.String getProcessdefinitionKey() {
		return this.processdefinitionKey;
	}
	public void setBusinformId(java.lang.String value) {
		this.businformId = value;
	}
	
	public java.lang.String getBusinformId() {
		return this.businformId;
	}
	public void setBusinformType(java.lang.String value) {
		this.businformType = value;
	}
	
	public java.lang.String getBusinformType() {
		return this.businformType;
	}
	

	public java.lang.String getStatus() {
		return status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getRowId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(!(obj instanceof WfProcinstance )) {return false;}
		if(this == obj) {return true;}
		WfProcinstance other = (WfProcinstance)obj;
		return new EqualsBuilder()
			.append(getRowId(),other.getRowId())
			.isEquals();
	}
}

