/*
 * Powered By [rapid-framework]
 * Web Site: http://www.rapid-framework.org.cn
 * Google Code: http://code.google.com/p/rapid-framework/
 * Since 2008 - 2013
 */

package com.neusoft.portal.query;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.neusoft.base.model.SearchModel;
import com.neusoft.portal.model.AppStar;
/**
 * database table: tb_app_star
 * database table comments: AppStar
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 */
public class AppStarQuery extends  SearchModel<AppStar> implements Serializable {
    
  private static final long serialVersionUID = 3148176768559230877L;
    

	  /**
     * tbid       db_column: tbid 
     */	
	private java.lang.Long tbid;
	  /**
     * appId       db_column: app_id 
     */	
	private java.lang.Long appId;
	  /**
     * memberId       db_column: member_id 
     */	
	private java.lang.Long memberId;
	  /**
     * starnum       db_column: starnum 
     */	
	private java.lang.Integer starnum;
	  /**
     * dt       db_column: dt 
     */	
	private java.util.Date dt;

	public java.lang.Long getTbid() {
		return this.tbid;
	}
	
	public void setTbid(java.lang.Long value) {
		this.tbid = value;
	}
	
	public java.lang.Long getAppId() {
		return this.appId;
	}
	
	public void setAppId(java.lang.Long value) {
		this.appId = value;
	}
	
	public java.lang.Long getMemberId() {
		return this.memberId;
	}
	
	public void setMemberId(java.lang.Long value) {
		this.memberId = value;
	}
	
	public java.lang.Integer getStarnum() {
		return this.starnum;
	}
	
	public void setStarnum(java.lang.Integer value) {
		this.starnum = value;
	}
	
	public java.util.Date getDt() {
		return this.dt;
	}
	
	public void setDt(java.util.Date value) {
		this.dt = value;
	}
	

	public String toString() {
		return ToStringBuilder.reflectionToString(this,ToStringStyle.MULTI_LINE_STYLE);
	}
	
}

